name: Deploy Vite App to GitHub Pages

# Ensure the workflow runs on push to main
on:
  push:
    branches:
      - main

# Set permissions to allow id-token requests
permissions:
  contents: read        # Default for most actions
  pages: write          # Required for Pages deployment
  id-token: write       # Required to fix your error

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Vite Github Pages Deployer
        uses: skywarth/vite-github-pages-deployer@v1.5.0
        with:
          public_base_path: "/"
          build_path: "./dist"
          package_manager: "npm"
